name: fpm-deployment

on: [push]
env:
  GCC_V: "13"
  PROJECT_NAME: "mfi"

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout üõéÔ∏è
      uses: actions/checkout@v2.3.1

    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: 3.x

    - name: Install fypp
      run: pip install --upgrade fypp

    - name: Generate ${{ env.PROJECT_NAME }}-fpm package üîß
      run: |
        make FYPPFLAGS="-DMFI_EXTENSIONS -DMFI_USE_CUBLAS"
        mkdir mfi-cublas
        cp -R src   mfi-cublas
        cp -R test  mfi-cublas
        cp fpm.toml mfi-cublas
        cp LICENSE  mfi-cublas

    - name: Install GFortran
      run: |
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${{ env.GCC_V }} 100 \
        --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-${{ env.GCC_V }} \
        --slave /usr/bin/gcov gcov /usr/bin/gcov-${{ env.GCC_V }}

    - name: Install Lapack and Blas
      run: |
        sudo apt install libblas3* liblapack3* libtmglib3* libcublas*

    - name: Install fpm latest release
      uses: fortran-lang/setup-fpm@v3
      with:
        fpm-version: 'v0.5.0'

    - name: Run fpm build ‚öô
      run: |
        fpm build --link-flag="-lcublas" --profile release

    # Update and deploy the f90 files generated by github-ci to the `PROJECT_NAME-fpm` branch.
    - name: Deploy üöÄ
      uses: JamesIves/github-pages-deploy-action@4.1.5
      if: github.event_name != 'pull_request'
      with:
        BRANCH: mfi-cublas
        FOLDER: mfi-cublas
